<?php

namespace Acme\ContentBundle\Repository;

use Acme\ContentBundle\Entity\Content;
use Doctrine\ORM\EntityRepository;

/**
 * ContentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContentRepository extends EntityRepository
{
    public function getNodeTranslationForUrl(
        $urlSlug,
        $locale = '',
        $includeDeleted = false,
       Content $toExclude = null
    ) {
        $qb = $this->createQueryBuilder('b');

        if (!empty($locale)) {

            $qb->andWhere('b.lang = :lang')
                ->setParameter('lang', $locale);
        }
        if (empty($urlSlug)) {
            $qb->andWhere('b.url IS NULL');
        } else {
            $qb->andWhere('b.url = :url');
            $qb->setParameter('url', $urlSlug);
        }
//        if (!is_null($toExclude)) {
//            $qb->andWhere('NOT b.id = :exclude_id')
//                ->setParameter('exclude_id', $toExclude->getId());
//        }


//        return $qb->getQuery()->getResult();
        return $qb->getQuery()->getOneOrNullResult();
    }
}
